### ISSUE TITLE
"Please reduce the length of the messages or completion" on short messages sent in long conversation

### ISSUE THREAD

**Issue by tomglynch** [yakGPT/yakGPT#13]
> This model's maximum context length is 4097 tokens. However, you requested 4295 tokens (3245 in the messages, 1050 in the completion). Please reduce the length of the messages or completion.

Keep getting this error once a conversation has gone on for a period of time. Is this expected or should the text being sent be truncated?

**Comment by yakGPT** [comment]
Haha, I'm glad it even bubbles that error up to the user (it's something I built on the last day before publishing). I will make the truncation logic smarter!

**Comment by yakGPT** [comment]
I just updated `main` to fix up the logic here and to now include an "Unlimited" setting, so you should run into this much less frequently!

**Comment by tomglynch** [comment]
Thanks @yakGPT, nice fix
