### ISSUE TITLE
Close mic when not in use

### ISSUE THREAD

**Issue by owenbrown** [yakGPT/yakGPT#2]
Presently, once the mic is used once, the mic for this app keeps listening, which puts the orange dot, 
<img width="206" alt="image" src="https://user-images.githubusercontent.com/1725390/228974979-9ed6e400-f8a3-4a3d-8d6d-7d1a00752dba.png">
on a Mac.

Even if YakGPT isn't using misusing the data, I can't use the orange indicator to know if my other apps are using the mic.

**Comment by yakGPT** [comment]
Very good point @owenbrown! This is something I noticed as well. I will noodle on this this afternoon.
