### ISSUE TITLE
Feature request: a way to input text via the keyboard as well

### ISSUE THREAD

**Issue by ljmatkins** [yakGPT/yakGPT#23]
It'd be nice if we could toggle a text box for cases when it's easier to type something than speak it.

(We could just use OpenAI's ChatGPT UI -- but it'd be handy to be able to do it all from one interface.)

**Comment by DalasNoin** [comment]
I am not quite sure what the issue is here, seems that you can just press the microphone button again to get back to the text box. Or do you want a combination of text and voice?

**Comment by ljmatkins** [comment]
Oh welp, I did not realize that was a button. Chalk this one up to user error! Thanks for the clarification.
