### ISSUE TITLE
This model's maximum context length is 4097 tokens.

### ISSUE THREAD

**Issue by gecersiznick** [yakGPT/yakGPT#26]
Full error message: "This model's maximum context length is 4097 tokens. However, you requested 4245 tokens (2980 in the messages, 1265 in the completion). Please reduce the length of the messages or completion."

How do I fix this error as per the suggestion of "Unlimited" option [here](https://github.com/yakGPT/yakGPT/issues/13#issuecomment-1492713778)? Thanks for the great tool by the way.

**Comment by plateaukao** [comment]
@yakGPT 

The code below will put all chat messages as context for each API request. In the end, it will always exceed token limit.

Is it possible to provide a fixed size option to allow users decide how many pre-conersations should be put in each request?
For example, keep first two (where usually the instructions are made), and the last 6 messages in each request.

https://github.com/yakGPT/YakGPT/blob/e4d39d9913e664e2ad48eb3eeaf70b9bc862b5c5/stores/ChatStore.ts#L249

**Comment by gecersiznick** [comment]
Figured the code has the `max_tokens` go "Unlimited" when `max_tokens === 0` and for that you need to use the slider and turn it down all the way to 0.
