### ISSUE TITLE
Feature Request: Rename Global Model to "Default Model for New Chats" and Allow Model Switching within Each Chat

### ISSUE THREAD

**Issue by randomsnowflake** [yakGPT/yakGPT#27]
- I use GPT 3.5 for quick and inexpensive solutions on certain topics. For more complex issues, I rely on GPT4.
- Rename the global model as "Default Model for New Chats" and allow switching models within each chat.

**Comment by yakGPT** [comment]
Hey @randomsnowflake I made switching models in-chat easier now via the UIController! If you'd like to contribute a PR to implement a "Default Model for New Chats" setting, I'd be very open to it!

**Comment by randomsnowflake** [comment]
I saw the change. Thanks.

One more little thing: Why is the initial speech2text model set to Azure? Users already provide their OpenAI API key, then why not use it by default?
