### ISSUE TITLE
[Dependencies] Does it need to have ~465 dependencies?

### ISSUE THREAD

**Issue by ManuLinares** [yakGPT/yakGPT#3]
Very cool project but as the title say I ask if it is a good practice to have such a long list of dependencies.

Having a large number of dependencies in a Node.js project can have several potential drawbacks:

- Increased complexity: Each dependency may have its own set of dependencies, leading to a complex web of dependencies that can be difficult to manage and debug. This can make it challenging to understand how different parts of the codebase interact with each other.

- Slower performance: Each dependency must be loaded and initialized at runtime, which can slow down the performance of the application. This can be particularly problematic on low-power devices or in applications that require high levels of performance.

- Increased security risks: Every dependency represents a potential security risk, as each one introduces new code that may contain vulnerabilities. This can be especially concerning if the dependencies are not well-maintained or are outdated.
 
- Compatibility issues: Dependencies may not always be compatible with each other or with the version of Node.js being used. This can result in difficult-to-diagnose issues that can be time-consuming to resolve.

- Maintenance burden: Each dependency must be updated and maintained over time to ensure that the project remains secure and functional. This can be a significant burden, especially if the dependencies are poorly documented or have complex APIs.

While having a large number of dependencies is not necessarily a bad thing in and of itself, it's important to carefully evaluate each one to ensure that it is necessary and that its benefits outweigh its potential drawbacks.

also, I think you forgot the `yarn next telemetry disable` step in the README -> Installation.

**Comment by yakGPT** [comment]
Hey @ManuLinares. Good shout about `next telemetry`, what dependencies do you think could be removed?

**Comment by yakGPT** [comment]
Closing for now ^_^
