### ISSUE TITLE
Feature request: Allow changing model up top (not settings); allow different models in different chats.

### ISSUE THREAD

**Issue by mpr1255** [yakGPT/yakGPT#30]
Simple as that really. This is a major feature of the chat.openai prompt. Would love to switch to this experience in browser (vimium keys etc.) but this is a real deal breaker unfortunately.

**Comment by yakGPT** [comment]
Hey! @mpr1255 you can now switch in the UIController! Does this work for you?
![image](https://user-images.githubusercontent.com/129409586/230793619-c9e4bde2-2e25-4a65-a1e5-7a3658705c10.png)
