### ISSUE TITLE
TTS support (via ElevenLabs?)

### ISSUE THREAD

**Issue by ben174** [yakGPT/yakGPT#4]
It would be great if you could optionally plug in your ElevenLabs API key and each chat response would be read aloud to you. If you're interested, I can fork and have a go at implementing this.

**Comment by zackproser** [comment]
Came here to ask for similar functionality. I would be very interested in this!

**Comment by distbit0** [comment]
Also there is the unofficial google translate tts api which is the only free one I am aware of, but requires text to be chunked into 100 word pieces and isn't the best voice either.

Also these are open source, actively maintained and self-hostable:

https://github.com/coqui-ai/TTS
https://github.com/neonbjb/tortoise-tts

**Comment by tluyben** [comment]
Also it's a good idea (imho) to add support for the native/free browser tts api; i did for this; https://github.com/cogentapps/chat-with-gpt/pull/55 but it's not merged yet. I use it myself as I find it good enough.

**Comment by yakGPT** [comment]
Good suggestions everyone! :) I'm working on this next and it should be merged today or tomorrow.

**Comment by yakGPT** [comment]
Just merged TTS support via ElevenLabs into `main`! This involved a big refactor how audio recording data is handled and a redesign and rebuild of the main "Input" component, so there might be some bugs abound. Let me know what you guys think!

**Comment by bgriffen** [comment]
Thanks! Would there be any docs on how this works? e.g. elevenlabs api key etc?
