### ISSUE TITLE
Suggestion: Improve TTS responsiveness by sending sentences as they generate (segmentation)

### ISSUE THREAD

**Issue by MikeStirner** [yakGPT/yakGPT#43]
To enhance the user experience and reduce pauses in the TTS playback, consider the following improvements:

1. Begin TTS playback as soon as the first sentence is generated. Implement a buffer or threshold (e.g., 1 second) to determine when to send the next sentence (or group of sentences ready to send) to the TTS engine.

2. Analyze punctuation marks and linguistic cues to dynamically group sentences before sending them to the TTS engine. If the second sentence is shorter than the buffer duration or threshold, wait until the next sentence is ready and send them together. Continue this process until all text has been sent to the TTS engine.

3. Handle edge cases, such as reaching the TTS engine's maximum character limit mid-sentence. In these cases, split the text at the nearest natural break (e.g., comma or period) and send the remaining text in the next TTS request.

This approach will minimize the waiting time for text generation, especially noticeable with GPT-4, and aims to provide a seamless TTS experience without pauses.

Please also update the play icon at the bottom left to play all the audio files in sequence.

Remember to consider the character limits of different TTS engines:

- ElevenLabs: 2,500 characters per request for non-subscribers, 5,000 characters for subscribers
- Azure (future?): ???

By incorporating these changes, the TTS experience will be smoother and more enjoyable for users. Thoughts?

**Comment by yakGPT** [comment]
Great idea @MikeStirner ! I also thought about this while implementing Azure STT & TTS, but wanted to keep it simple considering how huge [the PR](https://github.com/yakGPT/yakGPT/pull/46/files) already was. I'll noodle on this this afternoon!

**Comment by yakGPT** [comment]
Merged! Let me know what you think!

**Comment by MikeStirner** [comment]
It works great so far!
