### ISSUE TITLE
Questions: Why .yarn not in .gitignore, production .env files, yarn version

### ISSUE THREAD

**Issue by strlns** [yakGPT/yakGPT#44]
Sorry if these are dumb question. 
I am not used to Yarn and haven't used Vercel so far either.

Thank you for providing this nice frontend! 👍

As for my questions:

why is `.yarn` not in `.gitignore`?
Same for production `.env` files?

AFAIK, this should not be needed for deployment workflows, especially not on Vercel – but I might be wrong as I don't have any experience with Vercel. 

Usually, it should be possible to build during deployment without commiting the packages,
and handle build artifacts as well as production `.env` files during deployment, isolated from the main git repository.  

Here, packages aren't commited, but they aren't ignored either?

Or is my configuration strange?

I [created a branch in my fork](https://github.com/strlns/yakGPT/tree/update-lockfile) which
- updates lockfile after installing with newer yarn version
- adds `.yarn` to `.gitignore`
- adds any and all `.env`files to `.gitignore`, not only `.env.local`

I also added an `.nvmrc`, but that's probably not a useful change for most people. On my machine, yarn runs via nvm and is only installed in my environment for Node 18.

I did not create a PR because I don't know which changes would break existing workflows or are unwanted. The NVM thing is probably not relevant for most people.

But the things listed as bullet points I think should be sensible.

Maybe someone could check if there is a yarn lockfile compatible with both ARM and x64?

**Comment by yakGPT** [comment]
Hey, in my local dir, I only have `.yarn` in `~`. Happy to accept a PR to expand gitignore to all `.env` files!

**Comment by strlns** [comment]
Hi, I created a PR here:

https://github.com/yakGPT/yakGPT/pull/59

all .env files ignored
yarn lockfile is untouched
added .yarn to gitignore and .nvmrc to project root just in case for people who install the project locally with a setup similar to mine (yarn via nvm, local project install)

`.yarn` only in home directory happens depending on `yarnrc.yml` and depending on if you install the project globally, I guess? Shouldn't hurt to have it in gitignore.

**Comment by yakGPT** [comment]
Thx @strlns ! :)
