### ISSUE TITLE
Bug: BGCard images should have object-fit inline style

### ISSUE THREAD

**Issue by strlns** [yakGPT/yakGPT#45]
On some viewports, the carousel with images representing characters / preludes have distorted images.

As far as I can see, it's a matter of adding 
`style={{objectFit: "cover"}}`

or

`style={{objectFit: "contain"}}`

to this usage of the mantine `Image`component:

https://github.com/yakGPT/yakGPT/blob/fef4cae8ecded41aa2ae4c8a70d8adc0dc2cbd96/components/BGCard.tsx#L89

There was a direct property `objectFit` in previous version of mantine-ui, which is deprecated.
Of course you could also add this rule to a style defined with `useStyles`.

**Comment by yakGPT** [comment]
This indeed looks much better, thx for the pointer!
