### ISSUE TITLE
Exceeded model's max. context length should not stop me

### ISSUE THREAD

**Issue by alejandrogomez314** [yakGPT/yakGPT#55]
I'm getting the following message after a sufficiently long dialogue:

<img width="463" alt="Screenshot 2023-04-08 at 5 50 31 AM" src="https://user-images.githubusercontent.com/6588846/230715034-f638c107-0919-4efc-b9f5-64c2b4379a17.png">

I would like this banner to come up but not stop me from keep asking YakGPT questions. Is this a bug or a feature?

**Comment by Clueed** [comment]
You simply cannot submit a larger context to OpenAI API. There is no way around that. As the error message says, you _need_ to reduce it. Reducing it automatically by, e.g., dropping the oldest messages, which the user would need to be notified about as well, is, I think, less intuitive than displaying the error.

The message could be more explicit about what could be done about that by, for example, having a button to create new conversation or resetting the current one but that's not what you're asking. 

This can be closed, I think.

**Comment by alejandrogomez314** [comment]
Got it, I had the expectation of the app to work the same way ChatGPT does but didn't take into account that possibility in the implementation. I'll close this out.
