### ISSUE TITLE
Support for local llama indexes and text-based settings of how AI should behave.

### ISSUE THREAD

**Issue by takanomizuki** [yakGPT/yakGPT#69]
**Excellent, thank you for creating the UI.
Personally, I thought it would be very useful to create a tab list on the settings screen that would allow selection of the index created by the llama index, and the content of the index selected there would be reflected in the conversation.
So, create a script called /YakGPT/pages/api/llama_index.ts.
Paste the following contents.**

「import { NextApiRequest, NextApiResponse } from "next";
import { GPTTreeIndex, SimpleDirectoryReader } from "llama_index";

async function handler(req: NextApiRequest, res: NextApiResponse) {
  const { query, indexName } = req.body;

  // LlamaIndexを使用してインデックスを作成します
  const documents = SimpleDirectoryReader("data").load_data();
  const index = GPTTreeIndex.from_documents(documents);

  // カスタムプロンプトを設定
  function custom_prompt(query, text_name, chapter, page_number) {
    return (
      "You always tell the questioner the truth in a very clear and polite manner, but"
      "You always tell the questioner the truth in a very clear and polite manner, but you also believe in making the questioner think once by creating a question when it is generally better to create a question or when there is no instruction not to create a question."
      "In doing so, you stay close to the questioner by summarizing lengthy information. You also always try to clarify page sources and provide clear answers."
      f"\n\n{query}\nPage source: text_name}, chapter - {chapter}, page - {page_number}"
    );
  }

  // カスタムプロンプトをデフォルトプロンプトとしてインデックスに設定
  index.set_default_prompt(custom_prompt);

  // インデックスを使用して質問に回答します
  const answer = await index.query(query, mode="default");
  res.status(200).json({ answer });
}

export default handler;」

**Next, I tried to implement it by adding the following code to /YakGPT/components/SettingsModal.tsx but it was too difficult for me.**

「<Tabs.Panel value="index"> {/* 新しいタブ */}
  <Box style={{ paddingTop: "20px" }}>
    <Group position="apart" style={{ alignItems: "center" }}>
      <Text size="sm">インデックスを選択:</Text>
      <Select
        data={[
          { value: "index1", label: "インデックス1" },
          { value: "index2", label: "インデックス2" },
          // 他のインデックスオプションを追加
        ]}
        value={selectedIndex}
        onChange={(value) => handleIndexChange(value)}
        menuPortalTarget={document.body}
        styles={{
          menuPortal: (base: any) => ({ ...base, zIndex: 9999 }),
          menuPortal: () => ({ zIndex: 9999 })
        }}
        transition="skew-up"
        transitionDuration={200}
      />
    </Group>
  </Box>
</Tabs.Panel>」

**If you don't mind, it would be helpful if you could implement this feature so that the prompts for how the AI should behave can be customized based on the text in the settings.**

**Comment by yakGPT** [comment]
Hi @takanomizuki I don't think there is currently much interest in adding support for local llama. But thank you for writing in!
