### ISSUE TITLE
Error when editing API key

### ISSUE THREAD

**Issue by reustle** [yakGPT/yakGPT#7]
When I view the edit modal, I get this:

![image](https://user-images.githubusercontent.com/304560/229001232-8d8b6102-264e-4ecf-8594-f697ad6da5e7.png)

If I hit save without making any changes, it gives an error as the key isn't properly formatted (since it's a redacted version of what is saved). Maybe we can disable the save button unless the field has changed?

**Comment by yakGPT** [comment]
Thx for the report, fixed!
