### ISSUE TITLE
How do I put my API so that everyone can use it for free?

### ISSUE THREAD

**Issue by Mikkke99** [yakGPT/yakGPT#71]
Can you please tell me how to put your API so that everyone can use it for free? I am cloning a project on Vercel

**Comment by dev-msp** [comment]
Can you be more specific about what you want exactly? Do you mean you want to deploy a version of YakGPT that stores your API key as a secret, and allows any user to chat without providing their own API key? 

If so, you'll probably need to fork the app and modify it to support your use case. I'm not the maintainer, but part of the point of the application is that it works without depending on any server or backend secrets. My guess is that this won't be changing any time soon.

**Comment by Mikkke99** [comment]
> Can you be more specific about what you want exactly? Do you mean you want to deploy a version of YakGPT that stores your API key as a secret, and allows any user to chat without providing their own API key?
> 
> If so, you'll probably need to fork the app and modify it to support your use case. I'm not the maintainer, but part of the point of the application is that it works without depending on any server or backend secrets. My guess is that this won't be changing any time soon.

Yes, that's right, I want to pay for all API myself and let my users use chat for free, but I don't quite understand how it can be done, this script is very handy and I would like to implement my idea on it. If you have any ideas how to do it, please tell me

**Comment by dev-msp** [comment]
OK, I understand what you're trying to so. As it stands, YakGPT is designed to work as just a frontend, as I mentioned earlier. 

To use it how you describe, you would need to make changes to your version of the software. It would involve storing your API key server-side instead of letting your users enter their own. The frontend would then need to make chat requests to its own endpoint (i.e. `POST yakgpt.vercel.app/chat`), which would use your key to get the response from OpenAI. 

if you want to do the same thing with the text-to-speech and speech-to-text APIs, it would be a similar process.

**Comment by Mikkke99** [comment]
> OK, I understand what you're trying to so. As it stands, YakGPT is designed to work as just a frontend, as I mentioned earlier.
> 
> To use it how you describe, you would need to make changes to your version of the software. It would involve storing your API key server-side instead of letting your users enter their own. The frontend would then need to make chat requests to its own endpoint (i.e. `POST yakgpt.vercel.app/chat`), which would use your key to get the response from OpenAI.
> 
> if you want to do the same thing with the text-to-speech and speech-to-text APIs, it would be a similar process.

Thank you very much for your advice, I understand the gist but I don't know how to do it technically (I am just learning coding) I would be very grateful if you could explain what exactly I need to do with this code.

**Comment by dev-msp** [comment]
Sorry, that would take time and effort that I can't really afford to spend. Plus if someone does it for you, you haven't learned much about coding!

The best way to learn is to start playing with the YakGPT code yourself and reading about the related subjects: HTTP servers, NextJS, etc.

**Comment by wesbragagt** [comment]
YakGpt supports environment variable keys see https://github.com/yakGPT/yakGPT#add-to-envlocal%EF%B8%8F-local-use-only
