### ISSUE TITLE
Could not read whole reply when it's long.

### ISSUE THREAD

**Issue by deepchatwithai** [yakGPT/yakGPT#78]
This is a great project that make gpt has ability to have voice.

But I met a question: when the reply of gpt is long (like 200 words), it would not read the final part of reply.

Any guy met similar question?

**How to reproduce similar issue:** 

Ask it question like "how to build a repo on Github", you will get a step-by-step guide, and the voice would keep going to step4 or 5, but could not read to the last word.

**Comment by yakGPT** [comment]
Currently listening to the full guide on "how to build a repo on Github" and we're already past step 6 😅
