### ISSUE TITLE
nvm 14 fails

### ISSUE THREAD

**Issue by Neil-Sawhney** [yakGPT/yakGPT#8]
Steps to reproduce:

- nvm use 14.18.0
- yarn
- yarn build

Fails to compile due to ReferenceError

updating to nvm 16 fixes the issue

**Comment by yakGPT** [comment]
Hey @Neil-Sawhney node 14 is quite old! I recommend 16 indeed or someone just contributed a dockerfile if that helps you (see README)

**Comment by Neil-Sawhney** [comment]
> Hey @Neil-Sawhney node 14 is quite old! I recommend 16 indeed or someone just contributed a dockerfile if that helps you (see README)

I agree! Only mentioned it because node 14 was included in the acceptable requirements when running yarn
