### ISSUE TITLE
[Feature request] OpeanAI TTS

### ISSUE THREAD

**Issue by Adhithya03** [yakGPT/yakGPT#92]
Any plans on integerating opeanAI's official TTS into YAKGPT?

**Comment by dev-msp** [comment]
I opened a pull request: #93. But the maintainer hasn't been responsive for a number of months, so you're welcome to use my fork in the meantime.

**Comment by Adhithya03** [comment]
> I opened a pull request: #93. But the maintainer hasn't been responsive for a number of months, so you're welcome to use my fork in the meantime.

Thank you very much 🙏😊

**Comment by yakGPT** [comment]
Now merged, thanks so much @dev-msp
